# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "split_multisample_vcf"
description: Split multi-sample VCF files into individual single-sample VCF files
keywords:
  - vcf
  - split
  - bcftools
components:
  - bcftools/pluginsplit
input:
  - ch_vcf:
      type: file
      description: |
        Channel containing multi-sample VCF files with metadata.
        The meta map must contain 'sample_ids' key with a set of sample IDs in each VCF
        and a 'variant_type' key with the variant type (e.g. 'snv', 'sv').
        Structure: [ val(meta), path(vcf) ]
      pattern: "*.{vcf,vcf.gz}"
output:
  - split_vcf:
      type: file
      description: |
        Channel containing single-sample VCF files.
        Each output VCF contains variants for one sample with updated metadata:
        - id: individual sample ID
        - family_id: original multi-sample VCF ID
        - variant_type: preserved from input
        Structure: [ val(meta), path(vcf) ]
      pattern: "*.{vcf,vcf.gz}"
  - ch_family_to_samples:
      type: Tuple<String, List<String>>
      description: |
        Channel containing family IDs and sets of associated sample IDs
        Structure: [ val(family_id), val(sample_ids) ]
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@Schmytzi"
maintainers:
  - "@Schmytzi"
