lint:
  files_exist:
    - CITATIONS.md
    - CODE_OF_CONDUCT.md
    - assets/nf-core-nallo_logo_light.png
    - docs/README.md
    - docs/images/nf-core-nallo_logo_light.png
    - docs/images/nf-core-nallo_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/modules.config
    - conf/igenomes_ignored.config
    - conf/test_full.config
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-nallo_logo_light.png
    - docs/README.md
    - docs/images/nf-core-nallo_logo_light.png
    - docs/images/nf-core-nallo_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .prettierignore
  modules_config: false
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
nf_core_version: 3.1.2
repository_type: pipeline
template:
  author: Felix Lenner
  description: Long-read variant calling pipeline
  force: false
  is_nfcore: false
  name: nallo
  org: genomic-medicine-sweden
  outdir: .
  skip_features: []
  version: 0.5.0dev
