lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-nallo_logo_light.png
    - docs/images/nf-core-nallo_logo_light.png
    - docs/images/nf-core-nallo_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/modules.config
  files_unchanged:
    - nextflow.config
    - CODE_OF_CONDUCT.md
    - assets/nf-core-nallo_logo_light.png
    - docs/images/nf-core-nallo_logo_light.png
    - docs/images/nf-core-nallo_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
nf_core_version: 2.14.1
repository_type: pipeline
template:
  prefix: genomic-medicine-sweden
  skip: []
