# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "align"
description: Map reads to a reference genome using minimap2. Allows for input splitting and mixing in of mapped BAMs
keywords:
  - alignment
  - bam
  - cram
  - minimap2
components:
  - minimap2/align
  - samtools/merge
  - splitubam
input:
  - ch_ubam:
      type: file
      description: |
        The input channel containing unmapped BAM files.
        Structure: [ val(meta), path(bam) ]
      pattern: "*.{bam/cram/sam}"
  - ch_mapped_bam:
      type: file
      description: |
        Optional input channel containing mapped BAM files to be merged with the newly mapped BAMs.
        Structure: [ val(meta), path(bam), path(bai) ]
      pattern: "*.{bam/cram}{,.bai,.crai}"
  - ch_mmi:
      type: file
      description: |
        Channel containing minimap2 index files.
        Structure: [ val(meta), path(mmi) ]
      pattern: "*.mmi"
  - val_split_alignment:
      type: bool
      description: |
        Whether to split the input BAM files and align them in parallel.
        The number of splits is determined by the pipeline configuration.
output:
  - bam_bai:
      type: file
      description: |
        Channel containing mapped BAM and index files.
        Structure: [ val(meta), path(bam), path(bai) ]
      pattern: "*.bam"
authors:
  - "@Schmytzi"
maintainers:
  - "@Schmytzi"
