name: Add PR checklist comment
on:
  pull_request_target:
    types:
      - opened

jobs:
  add_pr_checklist_comment:
    runs-on: ubuntu-latest
    steps:
      # Checkout the default branch
      - uses: actions/checkout@v6

      # Add PR comment from file
      - uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: .github/pr_checklist_comment_body.md
