name: nf-core CI for master

# Run the workflow when:
#  - dispatched manually
#  - when a PR is opened or reopened to master branch
#  - the head branch of the pull request is updated, i.e. if fixes for a release are pushed last minute to dev.
on:
  workflow_dispatch:
    inputs:
      testbranch:
        description: "The specific branch you wish to utilize for the test execution."
        required: true
        default: "dev"
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - master
  pull_request_target:
    branches:
      - master

env:
  NXF_ANSI_LOG: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test-no-bed:
    name: Run pipeline with test data with no BED
    # Only run on push if this is the nf-core dev branch (merged PRs)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parameters:
          - "--bed=`null`"
        NXF_VER:
          - "23.04.0"
          - "latest-everything"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Disk space cleanup
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,docker --outdir ./results ${{ matrix.parameters }}
